name: LightMaker
main: com.yellowfortyfour.spigot.lightmaker.LightMakerPlugin
version: 0.0.2-SNAPSHOT
author: Fredrik Andersson (ProtonCavor)

#commands:
commands:
  b:
    description: sets data on block in hand
    usage: 'Usage: /b [c bulbid]|[d]'
  c:
    description: reads config
    usage: /c
  q:
    description: read and write sqllite db
    usage: /q

permissions:
  lightmaker.*:
    description: Defaulting all to false
    permission-message: You need permission <permission>  to use this command
    default: false        
  lightmaker.use:
    description: Permission to let user use lm commands lmon and lmoff
    default: false
  lightmaker.all:
    description: All permissions
    default: op
    children:
      lightmaker.*: true
